=== IhorTarkhan/Python/src/lab1/resources/sample.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT geometry (polygon)*>
        <!ELEMENT polygon (vertex+)>
        <!ATTLIST polygon id CDATA #REQUIRED>
        <!ELEMENT vertex EMPTY>
        <!ATTLIST vertex id CDATA #REQUIRED x CDATA #REQUIRED y CDATA #REQUIRED>

=== IhorTarkhan/Python/src/lab1/resources/sample.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE geometry SYSTEM "sample.dtd" >
<geometry>
    <polygon id="1">
        <vertex id="1" x="14" y="41"/>
        <vertex id="2" x="2.0" y="1.0"/>
        <vertex id="3" x="2.0" y="2.0"/>
    </polygon>
    <polygon id="2">
        <vertex id="4" x="-5.5" y="-6.7"/>
        <vertex id="5" x="12.5" y="-16.0"/>
    </polygon>
</geometry>
